sonar.projectKey=frontend-react
sonar.projectName=Frontend React
sonar.projectVersion=1.0

# Code source
sonar.sources=src

# 🔥 IMPORTANT : dire où sont les tests
sonar.tests=src

# fichiers tests
sonar.test.inclusions=src/**/__tests__/**,src/**/*.test.js,src/**/*.test.jsx

# exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.css

# coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# encodage
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000


sonar.token=sqa_61d6cd44f8e4567f61e75f0f9ac8bbb6c41efccf