sonar.projectKey=frontend-react
sonar.projectName=Frontend React
sonar.projectVersion=1.0

sonar.sources=src
sonar.inclusions=\
  src/components/common/**,\
  src/components/layout/**,\
  src/components/product/**,\
  src/context/CartContext.jsx,\
  src/hooks/useCart.js,\
  src/hooks/useCarousel.js,\
  src/hooks/useCategories.js,\
  src/hooks/useFilters.js,\
  src/hooks/useProducts.js,\
  src/pages/Cart/**,\
  src/pages/Home/**,\
  src/pages/Login/**,\
  src/pages/Orders/**,\
  src/pages/ProductDetails/**,\
  src/pages/Products/**,\
  src/pages/Profile/**,\
  src/pages/Register/**,\
  src/utils/filterProducts.js,\
  src/utils/formatPrice.js

sonar.exclusions=**/node_modules/**,**/dist/**,**/__tests__/**

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=yourToken

sonar.javascript.lcov.reportPaths=coverage/lcov.info