sonar.projectKey=frontend-react
sonar.projectName=Frontend React
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**

# means that we run the sonat test without coverage
# we don't have our own tests for the frontend
sonar.coverage.exclusions=**

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=Your_Token